---
title: "Exploratory data analysis - temperature and depth"
aauthor: "Ben Cresswell"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
 html_document:
    code_folding: show
    collapse: no
    df_print: paged
    fig_caption: yes
    fig_height: 4
    fig_width: 4
    highlight: textmate
    theme: spacelab
    toc: yes
    toc_float: yes
editor_options: 
  chunk_output_type: inline
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load required packages
```{r packages, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
library(tidyverse)
```

# Housekeeping
```{r warning=FALSE}
#rm(list=ls()) # Clear out environment if necessary
```

# Load shark and teleost T/P data
```{r}
load(file = "../data/Rdata/shark_tp_data.Rdata")
load(file = "../data/Rdata/teleost_tp_data.Rdata")
```



```{r}
teleost_tp_data %>% 
  ggplot() +
  geom_point(aes(x = detection_timestamp, y = Depth)) +
  facet_wrap(~transmitter_id)
```

```{r}
teleost_tp_data %>% 
  ggplot() +
  geom_point(aes(x = detection_timestamp, y = Depth)) +
  scale_y_reverse()
```


```{r}
shark_tp_data %>% 
  ggplot() +
  geom_point(aes(x = detection_timestamp, y = Temp)) +
  facet_wrap(~ transmitter_id)
```

```{r}
shark_tp_data %>% 
  ggplot() +
  geom_point(aes(x = detection_timestamp, y = Depth)) +
  scale_y_reverse() +
  facet_wrap(~transmitter_id)
```


```{r}
diurnal_sharks <- 
  shark_tp_data %>% 
  mutate(hour = hour(detection_timestamp)) %>% 
  mutate(tod = case_when(hour %in% (6:18) ~ "Day",
                         TRUE ~ "Night"))


```



```{r}
diurnal_sharks %>% 
  ggplot() +
    geom_point(aes(x = detection_timestamp, y = Depth)) +
    scale_y_reverse() +
    facet_wrap(~tod)
```


```{r}
diurnal_sharks %>% 
  ggplot() +
    geom_point(aes(x = detection_timestamp, y = Temp)) +
    facet_wrap(~tod)
```








