---
title: "Exploratory data analysis - temperature and depth"
aauthor: "Ben Cresswell"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
 html_document:
    code_folding: show
    collapse: no
    df_print: paged
    fig_caption: yes
    fig_height: 4
    fig_width: 4
    highlight: textmate
    theme: spacelab
    toc: yes
    toc_float: yes
editor_options: 
  chunk_output_type: inline
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load required packages
```{r packages, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
library(patchwork)
library(tidyverse)
```

# Housekeeping
```{r warning=FALSE}
#rm(list=ls()) # Clear out environment if necessary
```

# Load shark T/P data
```{r}
#load(file = "../data/Rdata/shark_tp_data.Rdata")
shark_tp_data
```


# Depth 

```{r}
shark_tp_data %>% 
  mutate(date = date(detection_timestamp),
         year_week = str_c(str_sub(isoyear(date), 3, 4),  "/", formatC(isoweek(date), format = "f", digits = 0, width = 2, flag = "0"))) %>% 
  filter(!is.na(Depth)) %>% 
  group_by(year_week) %>% 
  summarise(weekly_max_depth = max(Depth),
            weekly_min_depth = min(Depth),
            weekly_mean_depth = mean(Depth))

```



```{r}
shark_tp_data %>% 
  mutate(date = date(detection_timestamp),
         year_week = str_c(str_sub(isoyear(date), 3, 4),  "/", formatC(isoweek(date), format = "f", digits = 0, width = 2, flag = "0"))) %>% 
  filter(!is.na(Depth)) %>% 
  group_by(year_week) %>% 
  summarise(weekly_max_depth = max(Depth),
            weekly_min_depth = min(Depth),
            weekly_mean_depth = mean(Depth)) %>% 
  ggplot() +
  geom_point(aes(x = year_week, y = weekly_max_depth)) +
  #geom_point(aes(x = date, y = roll_mean), data = SST_comb3, colour = "blue") +
  #geom_line(aes(x = date, y = roll_mean), data = SST_comb3, colour = "blue") 
  #geom_smooth(aes(x = date, y = weekly_max_depth)) +
  scale_y_reverse() 
```


```{r}
max_dep_plot <- 
shark_tp_data %>% 
  mutate(date = date(detection_timestamp)) %>% 
  filter(!is.na(Depth)) %>% 
  group_by(date) %>% 
  summarise(daily_max_depth = max(Depth),
            daily_min_depth = min(Depth),
            daily_mean_depth = mean(Depth)) %>% 
  ungroup() %>% 
  ggplot() +
  geom_point(aes(x = date, y = max_depth)) +
  #geom_point(aes(x = date, y = roll_mean), data = SST_comb3, colour = "blue") +
  #geom_line(aes(x = date, y = roll_mean), data = SST_comb3, colour = "blue") 
  #geom_smooth(aes(x = date, y = max_depth)) +
  scale_y_reverse() 
```


```{r}
max_dep_plot/SST_plot
```


# Depth - by receiver location
```{r}
shark_tp_data %>% 
  #filter(station_name_long == 'Lagoon_2')# %>% # Just looking at Silver City for now as it is the only one with observations for the whole period
  ggplot() +
  geom_point(aes(x = detection_timestamp, y = Depth)) +
  scale_y_reverse()  +
  facet_wrap(~station_name)
```







Same with depth - pattern replicated by most individuals. 
Interesting to look at #14049 who didn't make as many deep moves and whose overall temperatures look higher than the others.

# Tease out max depths per day/week
```{r}
shark_dailydep <- 
shark_tp_data %>% 
  mutate(date = as_date(detection_timestamp)) %>% 
  group_by(date, station_name_long) %>% 
  filter(!is.na(Depth)) %>% 
  summarise(daily_max_depth = max(Depth))

shark_weeklydep <- 
shark_dailydep %>% 
  mutate(week = week(date),
         year = year(date)) %>% 
  mutate(year_week = paste(year, week)) %>% 
  group_by(year_week, station_name_long) %>% 
  summarise(weekly_max_depth = max(daily_max_depth)) #%>% 
  arrange(year)
```

# And plot
```{r}
shark_dailydep %>% 
  filter(station_name_long == 'Silver_City') %>% # Just looking at Silver City for now as it is the only one with observations for the whole period
  ggplot() +
  geom_point(aes(x = date, y = daily_max_depth)) +
  scale_y_reverse() 
 # facet_wrap(~transmitter_id)

shark_weeklydep %>% 
  filter(station_name_long == 'Silver_City') %>% # Just looking at Silver City for now as it is the only one with observations for the whole period
  ggplot() +
  geom_point(aes(x = year_week, y = weekly_max_depth)) +
  scale_y_reverse() 
 # facet_wrap(~transmitter_id)
```


```{r}
diurnal_sharks <- 
  shark_tp_data %>% 
  mutate(hour = hour(detection_timestamp)) %>% 
  mutate(tod = case_when(hour %in% (6:18) ~ "Day",
                         TRUE ~ "Night"))
```



```{r}
diurnal_sharks %>% 
  ggplot() +
    geom_point(aes(x = detection_timestamp, y = Depth)) +
    scale_y_reverse() +
    facet_wrap(~tod)
```


```{r}
diurnal_sharks %>% 
  ggplot() +
  geom_point(aes(x = detection_timestamp, y = Temp)) +
  geom_point(aes(x = time, y = temp), data = SSTcomb, colour = "blue") +
  facet_wrap(~tod)
```








