---
title: "Exploratory data analysis - teleost depth"
author: "Ben Cresswell"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
 html_document:
    code_folding: show
    collapse: no
    df_print: paged
    fig_caption: yes
    fig_height: 4
    fig_width: 7
    highlight: textmate
    theme: spacelab
    toc: yes
    toc_float: yes
editor_options: 
  chunk_output_type: inline
---


```{r include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source('packages.R')
#getwd()
#rm(list=ls()) # Clear out environment if necessary
```
# Load teleost T/P data
```{r}
load(file = "../data/Rdata/teleost_tp_data.Rdata")
```


```{r fig.width=10}
teleost_abacus_depth <- 
teleost_tp_data %>% 
  mutate(TID_spp = paste(transmitter_id, Scientific_name),
         detection_timestamp =date(detection_timestamp)) %>% 
  ggplot() +
  geom_point(aes(x = detection_timestamp, y = Depth)) +
  facet_wrap(~TID_spp) +
  #facet_wrap(~station_name_long) +
  theme_minimal() +
  xlab('\n Date')+
  ylab('Depth \n (m below sea surface)') +
  scale_x_date(date_breaks = "2 months", date_labels = '%b') +
  scale_y_reverse() +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5)) 
teleost_abacus_depth
ggsave(plot = teleost_abacus_depth, filename = "../output/teleost_abacus_depth.png", device = 'png', width = 180, height = 100, units = "mm")
```

Of the 10 tagged individuals, only 8 show up and only 3 of those present for the entire year

```{r}
teleost_tp_data %>% 
  mutate(date = date(detection_timestamp),
         TID_spp = paste(transmitter_id, Scientific_name)) %>% 
  filter(!is.na(Depth)) %>% 
  group_by(date, TID_spp) %>% 
  summarise(daily_max_depth = max(Depth),
            daily_min_depth = min(Depth),
            daily_mean_depth = mean(Depth)) %>% 
  ggplot() +
  geom_point(aes(x = date, y = daily_max_depth), colour = "red") +
  geom_point(aes(x = date, y = daily_min_depth), colour = "blue") +
  scale_x_date(date_breaks = "2 months", date_labels = '%b') +
  scale_y_reverse() +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5)) +
  theme_minimal() +
  xlab('\n Date')+
  ylab('Depth \n (m below sea surface)') +
  facet_wrap(~TID_spp)



```




```{r}
teleost_tp_data %>% 
  ggplot() +
  geom_point(aes(x = detection_timestamp, y = Depth)) +
  scale_y_reverse()
```

