---
title: "Wrangling ROV data"
aauthor: "Ben Cresswell"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
 html_document:
    code_folding: show
    collapse: no
    df_print: paged
    fig_caption: yes
    fig_height: 4
    fig_width: 4
    highlight: textmate
    theme: spacelab
    toc: yes
    toc_float: yes
editor_options: 
  chunk_output_type: inline
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load required packages
```{r packages, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
library(hms)
library(tidyverse)
```

# Housekeeping
```{r warning=FALSE}
rm(list=ls()) # Clear out environment if necessary
```

ROV records temperature and depth as part of its deployment metadata log. We have a number of deployments at Osprey Reef, from 


## Load
### Dive 1 from Deployment 22-02-2023, from 97 - 22m
```{r load-dep2, message=FALSE, warning=FALSE}
osplog2023_D1 <- read_csv('../data/ROV/2023-02-22 08-35-42 vehicle1.csv') %>% 
  mutate(Time = as_hms(clock.currentTime)) %>% 
  select(Time, altitudeRelative, temperature.temperature1, temperature.temperature2) %>% 
  filter(Time > parse_hms("08:39:00")) %>%  # Beginning of the first 90m+ transect
  filter(Time < parse_hms("08:59:00"))  # End of dive
```

### Dive 2 from Deployment 22-02-2023, from 97 - 22m
```{r load-dep2, message=FALSE, warning=FALSE}
osplog2023_D2 <- read_csv('../data/ROV/2023-02-22 08-35-42 vehicle1.csv') %>% 
  mutate(Time = as_hms(clock.currentTime)) %>% 
  select(Time, altitudeRelative, temperature.temperature1, temperature.temperature2) %>% 
  filter(Time > parse_hms("09:11:30")) %>%  # Beginning of the first 90m+ transect
  filter(Time < parse_hms("09:35:00"))  # End of dive
```



```{r}
  ggplot() +
  geom_point(aes(x = temperature.temperature2, y = altitudeRelative), data = osplog2023_D1) +
  geom_point(aes(x = temperature.temperature2, y = altitudeRelative), data = osplog2023_D2) +
  scale_x_continuous(limits = c(27,31))
```




















```{r}
ggplot() +
  geom_point(aes(x = time, y = temp), data = SST4mic, colour = "blue") +
  geom_line(aes(x = time, y = temp), data = SST4mic, colour = "blue") +
  geom_point(aes(x = time, y = temp), data = SST11mic, colour = "red") +
  geom_line(aes(x = time, y = temp), data = SST11mic, colour = "red") 
```


```{r}
SSTcomb <- 
  full_join(SST4mic, SST11mic)
```


```{r}
ggplot() +
  geom_point(aes(x = time, y = temp), data = SSTcomb, colour = "blue") +
  geom_line(aes(x = time, y = temp), data = SSTcomb, colour = "blue")
```



