---
title: "Exploratory data analysis - shark temperature and depth"
author: "Ben Cresswell"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
 html_document:
    code_folding: show
    collapse: no
    df_print: paged
    fig_caption: yes
    fig_height: 3
    fig_width: 9
    highlight: textmate
    theme: spacelab
    toc: yes
    toc_float: yes
editor_options: 
  chunk_output_type: inline
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r include=FALSE}
getwd()
source("code/packages.R")
#rm(list=ls()) # Clear out environment if necessary
```


# Load shark T/P data
```{r}
getwd()
load(file = "data/Rdata/shark_tp_data.Rdata")
```

Re-level the hourly variable so that morning/day is first and evening/night afterwards
```{r}
#time_levels <- c('7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '0', '1', '2', '3', '4', '5', '6')

##shark_tp_data <- shark_tp_data %>% mutate(hour = factor(hour, levels = time_levels))
```


## Temp and depth by hour
```{r}
hourly_shark_data <- 
shark_tp_data %>% 
  group_by(Season, hour) %>% 
  filter(!is.na(Depth)) %>% 
   summarise(max_depth = max(Depth),
            mean_depth = mean(Depth),
            median_depth = median(Depth),
            min_depth = min(Depth),
            sd_depth = mad(Depth),
            se_depth = std.error(Depth)) %>% 
  left_join(shark_tp_data %>% 
              group_by(Season, hour) %>% 
  filter(!is.na(Temp)) %>% 
  summarise(max_temp = max(Temp),
            mean_temp = mean(Temp),
            median_temp = median(Temp),
            min_temp = min(Temp),
            sd_temp = sd(Temp),
            se_temp = std.error(Temp))) %>% 
  mutate(Season = factor(Season, levels = c("Spring", "Summer", "Autumn", "Winter")))
```

# Mean depth use by hour ~ season
```{r fig.height=40/25.4, fig.width=160/25.4}
hr_meandepth <- hourly_shark_data %>% 
  ggplot() +
  annotate("rect", xmin = 0, xmax = 6, ymin = 80, ymax = 0, fill = "grey50", alpha = 0.5) +
  annotate("rect", xmin = 18, xmax = 24, ymin = 80, ymax = 0, fill = "grey50", alpha = 0.5) +
  geom_errorbar(aes(ymin = mean_depth-sd_depth, ymax = mean_depth+sd_depth, x = hour), width = 1.5, colour = "grey40", linewidth = 0.2) +
  geom_line(aes(x = hour, y = mean_depth), colour = "grey20") +
  geom_point(aes(x = hour, y = mean_depth, fill = Season), pch = 21, alpha = 0.5) +
  #geom_line(aes(x = hour, y = median_depth), colour = "grey20") +
  #geom_point(aes(x = hour, y = median_depth), pch = 21, fill = "green4", colour = "black") +
  scale_fill_manual(values = c("dodgerblue","red", "orange", "darkblue")) +
  scale_y_reverse() +
  #geom_vline(xintercept = c(6, 18), colour = "grey30", lwd = 0.3) +
  theme_minimal() +
  scale_x_continuous(limits = c(-1, 24), breaks = c(0, 6, 12, 18, 24)) +
  facet_wrap(~ Season, ncol = 4) +
  theme(legend.position = "none",
        axis.text.x = element_blank()) +
  ylab("Mean depth\n(m ± SD)") + 
  xlab(NULL)

hr_meandepth
```


# Max depth use by hour ~ season - prob don't need this
```{r fig.height=40/25.4, fig.width=160/25.4}
hourly_shark_data %>% 
  ggplot() +
  #geom_smooth(aes(x = hour, y = max_depth), method = "gam", formula = y~s(x, bs = "cs", k = 22), colour = "blue") +
  geom_line(aes(x = hour, y = max_depth), colour = "grey20") +
  geom_point(aes(x = hour, y = max_depth), pch = 21, fill = "grey", colour = "black") +
  scale_y_reverse() +
  geom_vline(xintercept = c(6, 18)) +
  theme_bw() +
  facet_wrap(~ Season, ncol = 4)
```



# Variation in depth use by hour ~ season (uses SD of mean depth)
```{r fig.height=50/25.4, fig.width=160/25.4}
hr_sddepth <- hourly_shark_data %>% 
  ggplot() +
  annotate("rect", xmin = 0, xmax = 6, ymin = 0, ymax = 35, fill = "grey50", alpha = 0.5) +
  annotate("rect", xmin = 18, xmax = 24, ymin = 0, ymax = 35, fill = "grey50", alpha = 0.5) +
  geom_line(aes(x = hour, y = sd_depth), colour = "grey20") +
  geom_point(aes(x = hour, y = sd_depth, fill = Season), pch = 21, alpha = 0.5) +
  scale_fill_manual(values = c("dodgerblue","red", "orange", "darkblue")) +
  #scale_y_reverse() +
  theme_minimal() +
  facet_wrap(~ Season, ncol = 4) +
  scale_x_continuous(limits = c(-1, 24), breaks = c(0, 6, 12, 18, 24)) +
  theme(legend.position = "none",
        strip.text = element_blank()) +
  ylab("Std. dev.\n(m)") + 
  xlab("Time of day")
```


```{r fig.height=100/25.4, fig.width=160/25.4}
hr_meandepth/hr_sddepth

hr_plot <- ggarrange(hr_meandepth, hr_sddepth, nrow = 2, label.y = 0.5, heights = c(1,0.65))
hr_plot
ggsave(hr_plot, file = "output/hr_plot.pdf", width = 170, height = 100, units = "mm", dpi = 300)


```


## Diurnal T/D
```{r}
diurnal_shark_data <- 
  shark_tp_data %>%
  group_by(Season, tod) %>% 
  filter(!is.na(Depth)) %>% 
  summarise(max_depth = max(Depth),
            mean_depth = mean(Depth),
            median_depth = median(Depth),
            min_depth = min(Depth),
            sd_depth = sd(Depth),
            se_depth = std.error(Depth)) %>% 
  left_join(shark_tp_data %>% 
              group_by(Season, tod) %>% 
              filter(!is.na(Temp)) %>% 
              summarise(max_temp = max(Temp),
                        mean_temp = mean(Temp),
                        median_temp = median(Temp),
                        min_temp = min(Temp),
                        sd_temp = sd(Temp),
                        se_temp = std.error(Temp)))
```




# Mean depth use by TOD ~ season
```{r fig.height=3, fig.width=9}
diurnal_shark_data %>% 
  ggplot() +
  #geom_line(aes(x = tod, y = mean_depth), colour = "grey20") +
  geom_point(aes(x = tod, y = mean_depth), pch = 21, fill = "grey", colour = "black") +
  geom_errorbar(aes(ymin = mean_depth-sd_depth, ymax = mean_depth+sd_depth, x = tod), width = 0.1, colour = "black") +
  scale_y_reverse() +
  geom_vline(xintercept = c(6, 18)) +
  theme_bw() +
  facet_wrap(~ Season, ncol = 4)
```
