---
title: "Shark data: weekly"
author: "Ben Cresswell"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
 html_document:
    code_folding: show
    collapse: no
    df_print: paged
    fig_caption: yes
    fig_height: 6
    #fig_width: 10
    out_width: 14
    highlight: textmate
    theme: spacelab
    toc: yes
    toc_float: yes
editor_options: 
  chunk_output_type: inline
---


```{r include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("code/packages.R")
rm(list=ls()) # Clear out environment if necessary
```


# Load data 
## Shark T/P data
```{r echo=FALSE, message=FALSE, warning=FALSE, fig.width=16, fig.height=6}
load(file = "data/Rdata/shark_tp_data.Rdata")
# Or, if you also want all the associated files loaded:
#source(knitr::purl("code/00_wrangle/wrangling_sensordata.Rmd", quiet = TRUE))
```

## SST
```{r echo=FALSE, message=FALSE, warning=FALSE, fig.width=16, fig.height=6}
load(file = "data/RData/SST.Rdata")
# Or, if you also want all the associated files loaded:
#source(knitr::purl("code/00_wrangle/wrangling_SSTdata.Rmd", quiet = TRUE))
```




# Weekly depth summary
```{r}
shark_weekly_depths <- 
shark_tp_data %>% 
  mutate(week_date = date(floor_date(detection_timestamp, "week"))) %>% 
  filter(!is.na(Depth)) %>% 
  group_by(week_date) %>% 
  summarise(weekly_max_depth = max(Depth),
            weekly_min_depth = min(Depth),
            weekly_mean_depth = mean(Depth),
            weekly_depth_sd = sd(Depth)) %>% 
  mutate(weekly_min_depth = if_else(weekly_min_depth <0, 0, weekly_min_depth))
shark_weekly_depths
```


## Plot weekly depths
```{r fig.width=16, fig.height=6}
shark_weekly_depth_plot <- 
shark_weekly_depths %>% 
  ggplot() +
  geom_line(aes(x = week_date, y = weekly_min_depth), colour = "blue") +
  geom_line(aes(x = week_date, y = weekly_mean_depth), colour = "grey30") +
  geom_smooth(aes(x = week_date, y = weekly_mean_depth), colour = "grey30", method = "gam", formula = y ~ s(x, bs = 'cs'), level = 0.95) +
  geom_line(aes(x = week_date, y = weekly_max_depth), colour = "red") +
  geom_smooth(aes(x = week_date, y = weekly_max_depth), colour = "red", method = "gam", formula = y ~ s(x, bs = 'cs'), level = 0.95) +
  scale_y_reverse() +
  theme_minimal() +
  xlab("Date") +
  ylab("Averaged weekly depths \n (m below sealevel)")
shark_weekly_depth_plot
```













