---
title: "Exploratory data analysis - shark weekly temperature patterns"
author: "Ben Cresswell"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
 html_document:
    code_download: true # set to false if you don't want a button to dl the Rmd
    code_folding: hide
    collapse: no
    df_print: paged
    fig_caption: yes
    fig_height: 6
    fig_width: 10
    highlight: textmate
    theme: spacelab
    toc: yes
    toc_float: yes
editor_options: 
  chunk_output_type: inline
output_dir: "docs"
documentclass: article
fontsize: 12pt
mainfont: Arial
mathfont: LiberationMono
monofont: DejaVu Sans Mono
classoption: a4paper
---


```{r}
knitr::opts_chunk$set(
	echo = TRUE,       # Set to F if you want to hide the code in the final doc (better to use "code folding: hide" in the YAML header and keep this on T)
	include = TRUE,    # Set to F if you want the code to run but no output in the final doc
	message = FALSE,   # 
	warning = FALSE,   #
	eval = TRUE       # If set to F will just print the text in between the chunks (and this setup chunk)
	)
```


```{r include=FALSE}
# Housekeeping
source("code/packages.R")
#rm(list=ls()) # Clear out environment if necessary
```

## Load data
```{r echo=FALSE, message=FALSE, warning=FALSE, fig.width=16, fig.height=6}
# Shark T/P data
load(file = "data/Rdata/shark_tp_data.Rdata")
# SST data
source(knitr::purl("code/00_wrangle/wrangling_SSTdata.Rmd", quiet = TRUE))
```


# Shark temps - weekly summary
-> Might not need this, given we have daily SST values
```{r}
shark_weekly_temps <- 
  shark_tp_data %>% 
  mutate(week_date = date(floor_date(detection_timestamp, "week"))) %>%
  filter(!is.na(Temp)) %>% 
  group_by(week_date) %>% 
  summarise(weekly_max_temp = max(Temp),
            weekly_min_temp = min(Temp),
            weekly_mean_temp = mean(Temp),
            weekly_temp_sd = sd(Temp))
shark_weekly_temps
```

# Plot weekly temps
```{r fig.width=16, fig.height=6}
shark_weekly_temps_plot <- 
shark_weekly_temps %>% 
  ggplot() +
  geom_line(aes(x = week_date, y = weekly_min_temp), colour = "blue") +
  #geom_smooth(aes(x = week_date, y = weekly_min_temp), colour = "blue", method = "gam", formula = y ~ s(x, bs = 'cs'), level = 0.95) +
  geom_smooth(aes(x = week_date, y = weekly_min_temp), colour = "blue", method = "loess", level = 0.95) +
  geom_line(aes(x = week_date, y = weekly_mean_temp), colour = "grey30") +
  geom_smooth(aes(x = week_date, y = weekly_mean_temp), colour = "grey30", method = "gam", formula = y ~ s(x, bs = 'cs'), level = 0.95) +
  geom_line(aes(x = week_date, y = weekly_max_temp), colour = "red") +
  geom_smooth(aes(x = week_date, y = weekly_max_temp), colour = "red", method = "gam", formula = y ~ s(x, bs = 'cs'), level = 0.95) +
  geom_line(aes(x = date, y = SST), data = SST, colour = "black") +
  scale_x_date(date_breaks = "1 months", date_labels = '%Y-%m') +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5)) +
  xlab("Date") +
  ylab("Averaged weekly depths \n (m below sealevel)")
shark_weekly_temps_plot
```


# TEMP PATTERNS BY INDIVIDUAL


# Shark temps - individual daily summary
Going to add in SST data at this point also
```{r}
shark_individual_daily_temps <- 
  shark_tp_data %>% 
  mutate(date = date(detection_timestamp)) %>% 
  filter(!is.na(Temp)) %>% 
  group_by(date, transmitter_id, Sex, TL) %>% 
  summarise(daily_max_temp = max(Temp),
            daily_min_temp = min(Temp),
            daily_mean_temp = mean(Temp),
            daily_temp_sd = sd(Temp)) %>% 
  full_join(SST)
shark_individual_daily_temps
```

## Plot
```{r fig.width=16, fig.height=6}
shark_individual_daily_temps_plot <- 
shark_individual_daily_temps %>% 
ggplot() +
  geom_line(aes(x = date, y = daily_max_temp), colour = "red") +
  geom_smooth(aes(x = date, y = daily_max_temp), colour = "red") +
  geom_line(aes(x = date, y = daily_min_temp), colour = "blue") +
  geom_smooth(aes(x = date, y = daily_min_temp), colour = "blue") +
  geom_line(aes(x = date, y = daily_mean_temp), colour = "grey40") +
  geom_smooth(aes(x = date, y = daily_mean_temp), colour = "grey40") +
  #geom_line(aes(x = week_date, y = weekly_rolling_mean), data = SSTcomb, colour = "black") +
  #geom_smooth(aes(x = week_date, y = weekly_rolling_mean), data = SSTcomb, colour = "black") +
  geom_line(aes(x = date, y = SST), data = SST, colour = "black") +
  #geom_line(aes(x = Month, y = SST), data = AMM_for_plot, colour = "black") +
  scale_x_date(date_breaks = "1 months", date_labels = '%Y-%m') +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5)) +
  #annotate("text", x = as.Date("2021-11-01"), y = 30.5, label = "a") +
  xlab("\nMonth of year") + 
  ylab("Temp (°C)") +
  facet_wrap(facets = "transmitter_id")


shark_individual_daily_temps_plot
```


# Shark temps - weekly summary - by individual
-> Might not need this, given we have daily SST values
```{r}
shark_individual_weekly_temps <- 
  shark_tp_data %>% 
  mutate(week_date = date(floor_date(detection_timestamp, "week"))) %>%
  filter(!is.na(Temp)) %>% 
  group_by(week_date, transmitter_id, Sex, TL) %>% 
  summarise(weekly_max_temp = max(Temp),
            weekly_min_temp = min(Temp),
            weekly_mean_temp = mean(Temp))
shark_individual_weekly_temps
```

# Plot individual weekly temps
```{r fig.width=16, fig.height=6}
shark_individual_weekly_temps_plot <- 
shark_individual_weekly_temps %>% 
  ggplot() +
  geom_line(aes(x = week_date, y = weekly_min_temp), colour = "blue") +
  #geom_smooth(aes(x = week_date, y = weekly_min_temp), colour = "blue", method = "gam", formula = y ~ s(x, bs = 'cs'), level = 0.95) +
  geom_smooth(aes(x = week_date, y = weekly_min_temp), colour = "blue", method = "loess", level = 0.95) +
  geom_line(aes(x = week_date, y = weekly_mean_temp), colour = "grey30") +
  geom_smooth(aes(x = week_date, y = weekly_mean_temp), colour = "grey30", method = "gam", formula = y ~ s(x, bs = 'cs'), level = 0.95) +
  geom_line(aes(x = week_date, y = weekly_max_temp), colour = "red") +
  geom_smooth(aes(x = week_date, y = weekly_max_temp), colour = "red", method = "gam", formula = y ~ s(x, bs = 'cs'), level = 0.95) +
  geom_line(aes(x = date, y = SST), data = SST, colour = "black") +
  scale_x_date(date_breaks = "1 months", date_labels = '%Y-%m') +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5)) +
  xlab("Date") +
  ylab("Averaged weekly depths \n (m below sealevel)") +
  facet_wrap(facets = "transmitter_id")

shark_individual_weekly_temps_plot
```


```{r}
#END
```


