---
title: "Shark temperature and depth - final model"
author: "Ben Cresswell"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
 html_document:
    code_folding: show
    collapse: no
    df_print: paged
    fig_caption: yes
    fig_height: 6
    fig_width: 10
    highlight: textmate
    theme: spacelab
    toc: yes
    toc_float: yes
editor_options: 
  chunk_output_type: inline
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	include = FALSE,
	message = FALSE,
	warning = FALSE)
```


```{r include=FALSE}
#rm(list=ls()) # Clear out environment if necessary
source("code/packages.R")
```


```{r}
# Load data
load(file = "data/Rdata/shark_individual_daily_td.Rdata")
```


# Fit model
Max depth (response variable) ~ SST * Season + Sex * TL (predictors, fixed effects) + 1|transmitter_id (predictor, random effect)
```{r}
sst_maxd_final <- glmmTMB(daily_movement ~ SST * Season + Sex * TL + (1|transmitter_id), data = shark_individual_daily_td, family = tweedie(), REML = TRUE)
```

## Model validation/diagnostics
```{r}
sst_maxd_final %>% simulateResiduals(plot=TRUE)
sst_maxd_final %>% performance::r2_nakagawa()
```

## Model investigation
```{r}
# Summary
#summary(sst_maxd_final)
# Summary of random effects
#sst_maxd_final %>% ranef()
sst_maxd_final %>% tidy(conf.int = TRUE)
```


# Save
```{r}
save(sst_maxd_final, file = "data/Rdata/final_model.Rdata")
```


```{r}
# END #
```