---
title: "Individual movement results - SST * Sex"
author: "Ben Cresswell"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
 html_document:
    code_folding: show
    collapse: no
    df_print: paged
    fig_caption: yes
    fig_height: 6
    fig_width: 10
    highlight: textmate
    theme: spacelab
    toc: yes
    toc_float: yes
editor_options: 
  chunk_output_type: inline
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	include = FALSE,
	message = FALSE,
	warning = FALSE)
```


```{r include=FALSE}
#rm(list=ls()) # Clear out environment if necessary
source("code/packages.R")
```


This document digs down into the interactive effect of SST and Sex on the magnitude of daily depth movements in individual sharks

# Load
```{r}
load(file = "data/Rdata/shark_individual_daily_td.Rdata")
```

# Load model
```{r}
load(file = "data/Rdata/final_model.Rdata")
```


```{r}
sst_maxd_final %>% emtrends("Sex", var = "TL") %>% regrid()# %>% contrast()
```


```{r  fig.width = 160/25.4, fig.height = 100/25.4}
Sex_TL_grid <- shark_individual_daily_td %>% 
    with(list(Sex = levels(Sex),
              TL = c(130, 150, 170)))
  
newdata_Sex_TL <- sst_maxd_final %>% 
  emmeans(~TL|Sex, at = Sex_TL_grid) %>% 
  regrid() %>% 
  as_tibble() %>% 
  mutate(TL = factor(TL),
         Sex_TL = factor(paste(Sex, TL)))
```


```{r  fig.width = 100/25.4, fig.height = 60/25.4}
(sex_TL_plot <- 
newdata_Sex_TL %>% 
  ggplot() +
  geom_linerange(aes(x = TL, y = response, ymin=asymp.LCL, ymax=asymp.UCL, colour = Sex, fill = Sex), colour = "grey40", position=position_dodge(0.5)) +
  geom_point(aes(x = TL, y = response, colour = Sex, fill = Sex, shape = Sex), colour = "grey20", position=position_dodge(0.5), size = 4) +
  scale_shape_manual(values = c(21,22)) +
  scale_fill_manual(values = c("darkblue", "dodgerblue")) +
  theme_minimal() +
  scale_y_continuous(limits = c(0, 110), breaks = c(0, 25, 50, 75, 100)) +
  #theme(plot.background = element_rect(fill = "transparent", colour = "black", linewidth = 1)) +
  #ylab("Daily depth movement (m)\n(e.m. mean ± 95%CI)") + 
  xlab("\nTotal length (cm)") +
  theme(legend.position='none',
        legend.background = element_rect(fill = "white", colour = "black"),
        axis.title.x = element_text(size = 8),
        axis.text.x = element_text(size = 8),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        legend.title = element_text(size = 8)))

```


# Save
```{r}
ggsave(sex_TL_plot, file = "output/Sex_TL_plot.pdf", width = 65, height = 50, units = "mm", dpi = 300)
```


# Combine with the Sex*SST plot
```{r  fig.width = 180/25.4, fig.height = 90/25.4}
SST_sex_TL_plot <- ggarrange(Sex_SST_plot2, sex_TL_plot, nrow = 1, label.y = 0.5, widths = c(1.1, 0.6))

SST_sex_TL_plot
```


# Save
```{r}
ggsave(SST_sex_TL_plot, file = "output/SST_sex_TL_plot.pdf", width = 170, height = 70, units = "mm", dpi = 300)
```



```{r}
# END #
```