---
title: "Modelling - shark temperature and depth - final models"
author: "Ben Cresswell"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
 html_document:
    code_folding: show
    collapse: no
    df_print: paged
    fig_caption: yes
    fig_height: 6
    fig_width: 10
    highlight: textmate
    theme: spacelab
    toc: yes
    toc_float: yes
editor_options: 
  chunk_output_type: inline
---


```{r include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("code/packages.R")
#rm(list=ls()) # Clear out environment if necessary
```




# Fit models

## Max depth ~ SST
```{r}
td_glmm1 <- glmmTMB(daily_max_depth ~ SST + (1|transmitter_id), data = shark_1_td, family = gaussian(), REML = TRUE)
td_glmm2 <- glmmTMB(daily_max_depth ~ SST + (SST|transmitter_id), data = shark_1_td, family = gaussian(), REML = TRUE)
td_glmm3 <- glmmTMB(daily_max_depth ~ SST * Season + (SST|transmitter_id), data = shark_1_td, family = gaussian(), REML = TRUE)
td_glmm4 <- glmmTMB(daily_max_depth ~ SST * Season + Sex + (SST|transmitter_id), data = shark_1_td, family = gaussian(), REML = TRUE)
td_glmm5 <- glmmTMB(daily_max_depth ~ SST * Sex + (SST|transmitter_id), data = shark_1_td, family = gaussian(), REML = TRUE)



```

```{r}
#plot_model(td_glmm3,  type='diag')[-2] %>% plot_grid()
td_glmm1 %>% simulateResiduals(plot=TRUE)
td_glmm2 %>% simulateResiduals(plot=TRUE)
td_glmm3 %>% simulateResiduals(plot=TRUE)
td_glmm4 %>% simulateResiduals(plot=TRUE)
td_glmm5 %>% simulateResiduals(plot=TRUE)
```
# Check AIC scores
```{r}
AIC(td_glmm1, td_glmm2, td_glmm3, td_glmm4, td_glmm5)
```

# Summary of random effects
```{r ranfeffects}
td_glmm1 %>% ranef()
td_glmm2 %>% ranef()
td_glmm3 %>% ranef()
```

## glmm R2
```{r}
td_glmm1 %>% performance::r2_nakagawa()
td_glmm2 %>% performance::r2_nakagawa()
td_glmm3 %>% performance::r2_nakagawa()
td_glmm4 %>% performance::r2_nakagawa()
```


## Summary table
```{r}
summary(td_glmm1)
summary(td_glmm2)
summary(td_glmm3)
summary(td_glmm4)
```





```{r}
td_glmm1 %>% ggemmeans(~ SST) %>% plot
td_glmm2 %>% ggemmeans(~ SST) %>% plot
td_glmm5 %>% ggemmeans(~ SST*Season) %>% plot
```


```{r}
td_glmm5 %>% ggemmeans(~ Sex) %>% plot
td_glmm5 %>% ggemmeans(~ Sex * SST) %>% plot
```






```{r}
td_glmm3 %>% 
  emmeans( ~ Season) %>% 
  contrast() %>% 
  confint()
```








